### PR TITLE
Switch NotNull reference over to Bean Validation API

### PR DESCRIPTION
**Pull request by twrist**
Fixes compilation issues using Maven and OpenJDK 8 on Centos 7 (and probably other distros, JDK versions etc.)

### CODE REVIEW

**Comment by twrist** [comment]
Not sure if it's related to the usage of Bean Validation, but having built using this I cannot authenticate with the Discovery server. The outgoing request doesn't appear malformed, however I'm only able to get a 500 response.  

For debugging purposes, this is the request being sent according to tcpflow:
```
139.099.141.051.50616-052.072.080.190.00080: POST /AmAlive HTTP/1.1
User-Agent: Java/1.8.0_181
Host: discovery.pyx.gianlu.xyz
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-type: application/x-www-form-urlencoded
Content-Length: 278


139.099.141.051.50616-052.072.080.190.00080: {"path":"/","port":443,"host":"desinc.club","publicKey":"37a031e1bb1df2fa048db92bdb57f4c4331b7fd8346fffa08de762928f4b2643f1bc3be2161d61eb92e306f2175fcdc4d9a0f64c45486cda27c6d9984642aaff3280201916ab9364ab0d20a59df27b924c139490ab2ee7cfe46a829c120e2f8e","metrics":"","secure":true}
```

**Comment by devgianlu** [comment]
Opened issue #2.

**Comment by devgianlu** [comment]
Try again now.

**Comment by devgianlu** [comment]
The Bean Validation API seems to be missing the `@Nullable` annotation which is very useful when using an IDE. I'll be using `org.jetbrains:annotations:15.0`.

**Pull request closed without merging**
